[package]
name = "rusty_shades"
version = "0.1.0"
authors = ["Capucho <jcapucho7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
naga = { git = "https://github.com/gfx-rs/naga.git", rev = "2b268c926c6dff5e366226a9502c06725107489d" }
paste = "1.0"
rsh-common = { path = "./rsh-common", features = ["naga"] }
rsh-lexer = { path = "./rsh-lexer" }
lalrpop-util = "0.19"
codespan-reporting = { version = "0.9", optional = true }

[features]
default = ["spirv"]
spirv = ["naga/spv-out"]

[build-dependencies]
lalrpop = "0.19"

[workspace]
default-members = ["rshc"]
members = ["rsh-lexer", "rsh-common", "rshc"]
