[package]
name = "rusty_shades"
version = "0.1.0"
authors = ["Capucho <jcapucho7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
internment = "0.4.0"
parze = { git = "https://github.com/zesterer/parze-new.git", rev = "d42e00dbd0d6efe083a266d7d456a822440c54e3" }
ordered-float = "1.0"
codespan-reporting = { version = "0.9", optional = true }
naga = { git = "https://github.com/gfx-rs/naga.git", features = [
    "spirv",
    "glsl-out"
], rev = "92c1ffb588fea859305b59b790dd08b3c943593d" }

[features]
default = ["codespan-reporting"]
