[package]
name = "rusty-shades"
version = "0.1.0"
authors = ["Capucho <jcapucho7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
naga = { git = "https://github.com/gfx-rs/naga.git", rev = "b76dff9d9ccb99b5e4f377f99d8b46017a181d26" }
rsh-common = { path = "./rsh-common", features = ["naga"] }
rsh-lexer = { path = "./rsh-lexer" }
rsh-ast = { path = "./rsh-ast" }
rsh-parser = { path = "./rsh-parser" }
lalrpop-util = "0.19"
codespan-reporting = { version = "0.9", optional = true }
petgraph = { version = "0.5", default-features = false }

[features]
default = ["spirv"]
spirv = ["naga/spv-out"]

[workspace]
default-members = ["rshc"]
members = ["rsh-lexer", "rsh-common", "rshc", "rsh-ast", "rsh-parser"]
